### ISSUE TITLE
`swarm info` pings the default cluster, not the one of the current organisation

### ISSUE THREAD

**Issue by zeisss** [giantswarm/cli#273]
E.g. for neofonie on leaseweb where there is no default app-service yet, the `swarm info` prints `cluster unreachable`, although the neofonie cluster is working fine.

**Comment by marians** [comment]
Especially with regard to `swarm info` we should either fix how ping works or how it's result is displayed. There we currently label it "Cluster status" where it currently is rather "API status" (right?)

I'd like this to be a deep ping (through to ap-service/cluster), because that's way more meaningful.

**Comment by marians** [comment]
As of now, the `swarm info` command presents the API`s ping response as "API status" (no longer "Cluster status").

I'd like to have a real "Cluster status" info in addition, since it would be indeed helpful to debug a situation where for example a cluster ID is set client side, but it's misspelled. I guess that should be the app-service's ping result, which should be depending on the cluster ID used.

**Comment by ewoutp** [comment]
+1

**Comment by marians** [comment]
Closing, as we no longer maintain this CLI.
