### ISSUE TITLE
Manage instances (start, stop, restart)

### ISSUE THREAD

**Issue by zeisss** [giantswarm/cli#386]
Regularly single instances fail. As a user it is currently impossible to manage single instances.

**Comment by ZeissS** [comment]
I added routes in https://github.com/giantswarm/api/pull/168 to our API.

@marians Do we need to think about how this  looks in the cli? I guess the behavior should be similar to to other places where we can issue instance commands (exec, logs,..).

**Comment by marians** [comment]
I changed the title of this issue to "Allow users to manage specific instances (start, stop, delete)" with the goal to discuss the high-level idea here.

We have requests to allow to remove a specific instance (if there are several instances of a component, to get rid of a "broken" one) and we'd like to be able to simply start single instances when they are down etc.

(I removed "restart" since this is pretty much covered in "stop" and "start".)

**Comment by marians** [comment]
Closing, as we no longer maintain this CLI.
