### ISSUE TITLE
Progress update when starting a service

### ISSUE THREAD

**Issue by teemow** [giantswarm/cli#4]
Starting apps can take a while. Especially when started the first time since images are pulled. As a user I only see "starting" and I don't know whats happening. 
#21 could be a first step.

Original Author: @luebken
Created at 26-08-2014 14:59:19
Gitlab: [giantswarm/cli!31](https://git.giantswarm.io/giantswarm/cli/issues/31)

**Comment by marians** [comment]
Some things we should do:
1. We should take a sneak peek into the docker client, since docker pull manages to update the terminal output of multiple lines.
2. Check how far the task API helps us already to get the details as drafted above. Then decide whether the draft and/or the task API needs to be tweaked.

Ping @ewoutp - Comment on 2. appreciated.

**Comment by marians** [comment]
@ZeissS FYI Moving the cursor upward is an ANSI escape code. See http://www.tldp.org/HOWTO/Bash-Prompt-HOWTO/x361.html

**Comment by ewoutp** [comment]
@marians ad 2) The task system does not give us exactly the same tree structure, so we cannot use a 1-1 mapping for that. However it does give us detailed information of state transitions in the entire tree.
I expect we should be able to get very close to the proposal without an excessive load on our system.

The only addition I can think of that may help is to have a `WaitForTasks` (in addition to `WaitForTask`) that blocks until one of the given tasks has finished. It can help simplify things in the client.

**Comment by ZeissS** [comment]
@marians the good old ANSI codes :dancer:

**Comment by marians** [comment]
Closing, as we no longer maintain this CLI.
