### ISSUE TITLE
Output should use colors and bold type

### ISSUE THREAD

**Issue by teemow** [giantswarm/cli#49]
Everybody loves colored terminal output. We could make good use of colors and bold text for
- Highlighting important keywords
- Highlighting error messages
- Structuring content in complex outputs like swarm status, swarm logs

and maybe more.

Original Author: @marian
Created at 21-11-2014 18:19:43
Gitlab: [giantswarm/cli!128](https://git.giantswarm.io/giantswarm/cli/issues/128)

**Comment by Nesurion** [comment]
After a talk with marian I'm going to implement the `status` and `start` command in the style he provided in his mockup and we'll review that together and see if it works for us or if we need to change things, in terms of styling.
We also want to introduce a new flag `--silent-output`, to enable users to get the unstyled output, even if they are using an interactive terminal.

**Comment by ZeissS** [comment]
How about `--no-color(s)`? Thats what this is normally called / what I would look for.

**Comment by Nesurion** [comment]
We talked about that, but decided to go with --simple-output for now, because that flag would not only deactivate colors, but also highlight words different. ie.:

with color mode:
Service **mole-rat** is up 

simple output:
Service 'mole-rat' is up 

but the flag naming is open for discussion of course

**Comment by marians** [comment]
Closing, as we no longer maintain this CLI.
