### ISSUE TITLE
Wrong error message if domain string is invalid

### ISSUE THREAD

**Issue by luebken** [giantswarm/cli#496]
swarm.json (domains contains a slash at the end)

```
{
  "name": "httplog_service",
  "components": {
    "webserver": {
      "image": "luebken/httplog",
      "ports": 8000,
      "domains": {
        "80": "httplog.leaseweb-alpha.giantswarm.io/"
      }
    }
  }
}
```

CLI command

```
$ swarm create
Creating 'httplog_service' in the 'luebken/dev' environment…
Cannot create service due to a validation error in 'swarm.json'.

    Validation error: invalid service definition: invalid format for domains: Port must be a number, got 'httplog.leaseweb-alpha.giantswarm.io': strconv.ParseInt: parsing "httplog.leaseweb-alpha.giantswarm.io": invalid syntax

```

**Comment by marians** [comment]
I agree the error message here isn't helpful.

This is a funny case, because there are two errors in the definition:

- The port key in the "domains" object has to match the port in the "ports" setting (80 != 8000)
- The domain contains the `/`character at the end

If we can, I'd love to report errors on both details.

**Comment by ZeissS** [comment]
@marians Multiple errors would be https://github.com/giantswarm/app-service/issues/102

**Comment by marians** [comment]
Closing, as we no longer maintain this CLI.
